version: "3"
services:
  etcd:
    image: quay.io/coreos/etcd
    container_name: etcd-node
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
       - "7379:2379"
       - "7380:2380"
    user: root
    volumes:
      - "/root/docker/etcd/etcd-data:/etcd-data"
    environment:
      - "ETCDCTL_API=3"
      - "ETCD_ADVERTISE_CLIENT_URLS=http://119.23.57.143:7379"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://119.23.57.143:7380"
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_INITIAL_CLUSTER=node1=http://47.112.210.86:7380,node2=http://119.23.57.143:7380,node3=http://119.23.40.36:7380"
      - "ETCD_NAME=node1"
      - "ETCD_DATA_DIR=/etcd-data"
      - "ETCD_INITIAL_CLUSTER_TOKEN=etcd-token"
      - "ETCD_INITIAL_CLUSTER_STATE=new"
    networks:
      - etcdnet

networks:
  etcdnet:
    driver: bridge